---
# steps taken from task keys.yml in the role ivansible.lin_enter

- name: authorize public ssh keys (and ensure keyfile permissions)
  authorized_key:
    user: "{{ certbot_replica_user }}"
    key: "{{ lookup('pipe', keygen_cmd) }}"
    comment: "{{ item |basename |regex_replace('[.]key$') }}"
  vars:
    # deliberately use ';' in the pipe to ignore chmod errors
    keygen_cmd: 'chmod 600 "{{ item }}"; ssh-keygen -y -f "{{ item }}"'
  loop: "{{ certbot_replica_ssh_keys }}"
  loop_control:
    label: "{{ item |basename }}"
...
