---
# steps taken from role ivansible.lin_enter task keys.yml

- name: fix local key files permissions for ssh-keygen (ok to fail)
  file:
    path: "{{ item }}"
    mode: 0600
  loop: "{{ certbot_replica_ssh_keys }}"
  loop_control:
    label: "{{ item | basename }}"
  connection: local
  ignore_errors: yes

- name: authorize public ssh keys
  authorized_key:
    user: "{{ certbot_replica_user }}"
    key: "{{ lookup('pipe', 'ssh-keygen -y -f \"{{ item }}\"') }}"
    comment: "{{ item | basename | regex_replace('[.]key$') }}"
    state: present
  loop: "{{ certbot_replica_ssh_keys }}"
  loop_control:
    label: "{{ item | basename }}"
...
