---
- name: use import to become root globally
  import_tasks: root.yml
  become: true
  tags: le_replica_all

- name: setup certbot master
  import_role:
    name: ivansible.cert_master
  vars:
    certbot_master_replica_hosts: "{{ ansible_play_hosts }}"
  delegate_to: "{{ certbot_master_host }}"
  run_once: yes
  when: certbot_master_host is defined
  tags: le_replica_master

- name: run postponed handlers now
  include_tasks: flush-handlers.yml
...
