---
# handlers file for ivansible.cert_replica

- name: run certbot once to create directory structure in /etc
  command: certbot
  failed_when: false
  become: yes

- name: run receive handler once to fix file/directory permissions
  command: "{{ certbot_replica_handler }}"
  become: yes
  ignore_errors: yes
  no_log: true
...
